# Generated by Django 5.2.9 on 2025-12-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
