# Generated by Django 5.2.9 on 2025-12-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="plans.tag"
            ),
        ),
    ]
