# Generated by Django 5.2.9 on 2025-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_plan_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="current_markdown",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
