# Generated by Django 5.2.9 on 2025-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_planversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["scope", "name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="scope",
            field=models.CharField(
                choices=[
                    ("TARGET", "Target"),
                    ("FOCUS", "Focus"),
                    ("WORKOUT", "Workout"),
                ],
                default="TARGET",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("scope", "name"), name="uniq_tag_scope_name"
            ),
        ),
    ]
