# Generated by Django 5.2.9 on 2025-12-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_alter_tag_options_tag_scope_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("is_unsorted", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="tags",
        ),
        migrations.AddField(
            model_name="plan",
            name="duration_days",
            field=models.PositiveIntegerField(default=84),
        ),
        migrations.AddField(
            model_name="plan",
            name="goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="start_date",
            field=models.DateField(default="2025-12-28"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="targets",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"scope": "TARGET"},
                related_name="plans_as_target",
                to="plans.tag",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="current_markdown",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_offset_days", models.PositiveIntegerField()),
                ("duration_days", models.PositiveIntegerField()),
                ("repeat", models.PositiveIntegerField(default=1)),
                ("note", models.TextField(blank=True)),
                (
                    "foci",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"scope": "FOCUS"},
                        related_name="blocks_as_focus",
                        to="plans.tag",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["start_offset_days", "id"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("offset_days", models.PositiveIntegerField()),
                ("type", models.CharField(blank=True, max_length=30)),
                ("note", models.TextField(blank=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="plans.block",
                    ),
                ),
            ],
            options={
                "ordering": ["offset_days", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("sets", models.PositiveIntegerField(blank=True, null=True)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("distance", models.CharField(blank=True, max_length=50)),
                ("duration_min", models.PositiveIntegerField(blank=True, null=True)),
                ("intensity", models.CharField(blank=True, max_length=50)),
                ("rest_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "alternatives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alternative_for_items",
                        to="plans.exercise",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_items",
                        to="plans.exercise",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"scope": "WORKOUT"},
                        related_name="workout_items_as_tag",
                        to="plans.tag",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="plans.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
