# Generated by Django 5.2.9 on 2025-12-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_exercise_remove_plan_description_remove_plan_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
