# Generated by Django 5.2.9 on 2025-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0010_workoutitemsession_workoutset"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutset",
            name="rir_or_rpe",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
