# Generated by Django 5.2.9 on 2026-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_workoutset_rir_or_rpe"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
